// Automatically generated by astro-icon
// 2f92b8cc9d18bc58e8d8b8256b4dbaa90ffdc2e24d451ad1a5f590ed397725f4

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "fa:soundcloud"
		| "material-symbols:download"
		| "material-symbols:copyright-outline"
		| "mdi:twitter"
		| "mdi:github"
		| "mdi:link-variant"
		| "mdi:download";
}