// Automatically generated by astro-icon
// 5984ce74f0e6b26e00aba701e3a27596125200b225007b2b4f7f176eb5d4770b

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "mdi:twitter"
		| "mdi:github"
		| "mdi:link-variant"
		| "mdi:download";
}