name = "snorre-io"
compatibility_date = "2022-11-07"
node_compat = true
pages_build_output_dir = "dist"


[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "snorre-io-prod"
database_id = "0eca1499-0169-474b-96ab-a0607c1d43dc"
preview_database_id = "DB"

[env.preview]
name = "preview"
[[env.preview.d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "snorre-io-preview"
database_id = "6ae44082-da8c-4f91-bc9a-0e1d9bd4e4a2"